// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/data.jsondata;
import ballerina/http;
import ballerina/jballerina.java;
import ballerina/lang.regexp;
import ballerina/log;
import ballerina/uuid;
import ballerinax/mistral;

const DEFAULT_MISTRAL_AI_SERVICE_URL = "https://api.mistral.ai/v1";
const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;
const PROVIDER_NAME = "mistral_ai";
const CHAT_COMPLETIONS_PATH = "/chat/completions";
# The payload Mistral sends as the last event of a chat completion stream.
const DONE_SENTINEL = "[DONE]";
# Upper bound on how much of an upstream error body is quoted back in an error
# message, so a large or unexpected response cannot dominate the message.
const MAX_ERROR_DETAIL_LENGTH = 512;

# MistralAiProvider is a client class that provides an interface for interacting with Mistral AI Large Language Models.
@display {
    label: "Mistral Model Provider"
}
public isolated client class ModelProvider {
    *ai:ModelProvider;
    private final mistral:Client llmClient;
    // Raw HTTP client used for the streaming endpoint; the generated `mistral:Client`
    // binds responses to a single value and cannot consume Server-Sent Events.
    private final http:Client streamClient;
    private final string modelType;
    private final decimal temperature;
    private final int maxTokens;

    # # Initializes the Mistral AI model with the given connection configuration and model configuration.
    #
    # + apiKey - The Mistral AI API key
    # + modelType - The Mistral AI model name
    # + serviceUrl - The base URL of Mistral AI API endpoint
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `nil` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "API Key"} string apiKey,
            @display {label: "Model Type"} MISTRAL_AI_MODEL_NAMES modelType,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_MISTRAL_AI_SERVICE_URL,
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal temperature = DEFAULT_TEMPERATURE,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig
    ) returns ai:Error? {

        mistral:ConnectionConfig mistralConfig = {
            auth: {token: apiKey},
            httpVersion: connectionConfig.httpVersion,
            http1Settings: connectionConfig.http1Settings ?: {},
            http2Settings: connectionConfig?.http2Settings ?: {},
            timeout: connectionConfig.timeout,
            forwarded: connectionConfig.forwarded,
            poolConfig: connectionConfig?.poolConfig,
            cache: connectionConfig?.cache ?: {},
            compression: connectionConfig.compression,
            circuitBreaker: connectionConfig?.circuitBreaker,
            retryConfig: connectionConfig?.retryConfig,
            responseLimits: connectionConfig?.responseLimits ?: {},
            secureSocket: connectionConfig?.secureSocket,
            proxy: connectionConfig?.proxy,
            validation: connectionConfig.validation
        };

        mistral:Client|error llmClient = new (mistralConfig, serviceUrl);
        if llmClient is error {
            return error ai:Error("Failed to initialize MistralAiProvider", llmClient);
        }

        // Mirrors `mistralConfig` field for field: the streaming endpoint must honour
        // the same proxy, TLS, pooling and retry settings as `chat`, or a deployment
        // behind a proxy or a custom CA would work for `chat` and fail for `chatAsStream`.
        http:ClientConfiguration streamClientConfig = {
            auth: {token: apiKey},
            httpVersion: connectionConfig.httpVersion,
            http1Settings: connectionConfig.http1Settings ?: {},
            http2Settings: connectionConfig?.http2Settings ?: {},
            timeout: connectionConfig.timeout,
            forwarded: connectionConfig.forwarded,
            poolConfig: connectionConfig?.poolConfig,
            cache: connectionConfig?.cache ?: {},
            compression: connectionConfig.compression,
            circuitBreaker: connectionConfig?.circuitBreaker,
            retryConfig: connectionConfig?.retryConfig,
            responseLimits: connectionConfig?.responseLimits ?: {},
            secureSocket: connectionConfig?.secureSocket,
            proxy: connectionConfig?.proxy,
            validation: connectionConfig.validation
        };
        http:Client|error streamClient = new (serviceUrl, streamClientConfig);
        if streamClient is error {
            return error ai:Error("Failed to initialize the Mistral AI streaming client", streamClient);
        }

        self.llmClient = llmClient;
        self.streamClient = streamClient;
        self.modelType = modelType;
        self.temperature = temperature;
        self.maxTokens = maxTokens;
    }

    # Uses function call API to determine next function to be called
    #
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Returns an array of ai:ChatAssistantMessage or an ai:LlmError in case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools, string? stop = ())
        returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider(PROVIDER_NAME);
        if stop is string {
            span.addStopSequence(stop);
        }
        span.addTemperature(self.temperature);
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        if tools.length() > 0 {
            span.addTools(tools);
        }
        mistral:ChatCompletionRequest|ai:Error request = self.buildChatCompletionRequest(messages, tools, stop, false);
        if request is ai:Error {
            span.close(request);
            return request;
        }

        mistral:ChatCompletionResponse|error response = self.llmClient->/chat/completions.post(request);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            span.close(err);
            return err;
        }

        string? responseId = response.id;
        if responseId is string {
            span.addResponseId(responseId);
        }
        int? inputTokens = response.usage?.promptTokens;
        if inputTokens is int {
            span.addInputTokenCount(inputTokens);
        }
        int? outputTokens = response.usage?.completionTokens;
        if outputTokens is int {
            span.addOutputTokenCount(outputTokens);
        }

        mistral:ChatCompletionChoice[]? choices = response.choices;
        string? finishReason = (choices !is () && choices.length() > 0) ? choices[0].finishReason : ();
        if finishReason is string {
            span.addFinishReason(finishReason);
        }
        ai:ChatAssistantMessage|ai:Error result = self.getAssistantMessage(response);
        if result is ai:Error {
            span.close(result);
            return result;
        }

        span.addOutputMessages(result);
        span.addOutputType(observe:TEXT);
        span.close();
        return result;
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
                returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.mistral.Generator"
    } external;

    # Sends a streaming chat request to the Mistral AI model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - A stream of chat message chunks, or an error in case of failures
    isolated remote function chatAsStream(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools = [], string? stop = ())
            returns stream<ai:ChatMessageChunk, ai:Error?>|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider(PROVIDER_NAME);
        if stop is string {
            span.addStopSequence(stop);
        }
        span.addTemperature(self.temperature);
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }
        if tools.length() > 0 {
            span.addTools(tools);
        }

        mistral:ChatCompletionRequest|ai:Error request = self.buildChatCompletionRequest(messages, tools, stop, true);
        if request is ai:Error {
            span.close(request);
            return request;
        }

        // `jsondata:toJson` is required here: the `mistral` records carry
        // `@jsondata:Name` annotations, so a plain `toJson()` would emit the
        // Ballerina field names (`maxTokens`, `toolCalls`) instead of the wire ones.
        http:Response|error response = self.streamClient->post(CHAT_COMPLETIONS_PATH, jsondata:toJson(request));
        if response is error {
            return closeSpanWith(span,
                    error ai:LlmConnectionError("Error while connecting to the model for streaming", response));
        }
        if response.statusCode != http:STATUS_OK {
            // A non-2xx response (e.g. rate limiting, invalid model) is returned as a
            // plain JSON error body, not an SSE stream. Surface it instead of failing
            // with a misleading "not text/event-stream" error from getSseEventStream().
            return closeSpanWith(span, error ai:LlmConnectionError(
                    string `Model returned an error while streaming (HTTP ${response.statusCode}): ${
                        getErrorResponseDetail(response)}`));
        }
        stream<http:SseEvent, error?>|error sseStream = response.getSseEventStream();
        if sseStream is error {
            return closeSpanWith(span,
                    error ai:LlmInvalidResponseError("Failed to open the SSE stream from the model", sseStream));
        }
        // The iterator owns `sseStream` and `span` from here: it closes both exactly
        // once, on `[DONE]`, exhaustion, an error, or an explicit `close()`.
        stream<ai:ChatMessageChunk, ai:Error?> chunkStream = new (new MistralChunkIterator(sseStream, span));
        return chunkStream;
    }

    # Sends a streaming chat request to the model using the given prompt and streams
    # back the generated answer as text fragments.
    #
    # Streaming produces text only: structured types have no valid intermediate state, so use
    # `generate` for structured output.
    #
    # + prompt - The prompt to use in the chat request
    # + return - A stream of text fragments, or an error if generation fails
    isolated remote function generateAsStream(ai:Prompt prompt) returns stream<string, ai:Error?>|ai:Error {
        stream<ai:ChatMessageChunk, ai:Error?> chunks = check self->chatAsStream({role: ai:USER, content: prompt});
        return new stream<string, ai:Error?>(new ChunkTextIterator(chunks));
    }

    # Builds the Mistral chat completion request shared by `chat` and `chatAsStream`.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be exposed to the model
    # + stop - Stop sequence to stop the completion
    # + streaming - Whether the model should stream the response back
    # + return - The mapped request, or an error if the messages could not be mapped
    private isolated function buildChatCompletionRequest(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop, boolean streaming)
            returns mistral:ChatCompletionRequest|ai:Error {
        mistral:ChatCompletionRequest request = {
            model: self.modelType,
            stop,
            messages: check self.mapToMistralMessageRecords(messages),
            temperature: self.temperature,
            maxTokens: self.maxTokens,
            'stream: streaming
        };
        if tools.length() > 0 {
            mistral:Tool[] mistralTools = [];
            foreach ai:ChatCompletionFunctions tool in tools {
                mistralTools.push({
                    'function: {
                        name: tool.name,
                        description: tool.description,
                        strict: false,
                        parameters: tool.parameters ?: {}
                    }
                });
            }
            request.tools = mistralTools;
        }
        return request;
    }

    # Generates a random tool ID.
    #
    # + return - A random tool ID string
    private isolated function generateToolId() returns string {
        string randomToolId = "";
        string randomId = uuid:createRandomUuid();
        regexp:RegExp alphanumericPattern = re `[a-zA-Z0-9]`;
        int iterationCount = 0;

        foreach string character in randomId {
            if alphanumericPattern.isFullMatch(character) {
                randomToolId = randomToolId + character;
                iterationCount = iterationCount + 1;
            }
            if iterationCount == 9 {
                break;
            }
        }
        return randomToolId;
    }

    private isolated function mapToMistralMessageRecords(ai:ChatMessage[]|ai:ChatUserMessage messages)
    returns MistralMessages[]|ai:Error {
        MistralMessages[] mistralMessages = [];
        if messages is ai:ChatUserMessage {
            mistralMessages.push(check self.mapToMistralMessage(messages));
            return mistralMessages;
        }
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatUserMessage|ai:ChatSystemMessage {
                mistralMessages.push(check self.mapToMistralMessage(message));
            } else if message is ai:ChatAssistantMessage {
                ai:FunctionCall[]? toolCalls = message.toolCalls;
                mistral:AssistantMessage mistralAssistantMessage = {role: ai:ASSISTANT, content: message.content};
                if toolCalls is ai:FunctionCall[] {
                    mistral:FunctionCall functionCall = {name: toolCalls[0].name, arguments: toolCalls[0].arguments.toJsonString()};
                    mistral:ToolCall[] toolCall = [{'function: functionCall, id: toolCalls[0]?.id ?: self.generateToolId()}];
                    mistralAssistantMessage.toolCalls = toolCall;
                }
                mistralMessages.push(mistralAssistantMessage);
            } else {
                mistral:ToolMessage mistralToolMessage = {
                    role: "tool",
                    content: message.content,
                    toolCallId: message.id ?: self.generateToolId()
                };
                mistralMessages.push(mistralToolMessage);
            }
        }
        return mistralMessages;
    }

    # Extracts assistant messages from a Mistral chat completion response.
    #
    # + response - The response from LLM
    # + return - An array of ai:ChatAssistantMessage records
    private isolated function getAssistantMessage(mistral:ChatCompletionResponse response)
        returns ai:ChatAssistantMessage|ai:LlmError {
        mistral:ChatCompletionChoice[]? choices = response.choices;
        if choices is () || choices.length() == 0 {
            return error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
        }
        mistral:AssistantMessage message = choices[0].message;
        string|mistral:ContentChunk[]? content = message?.content;
        if content is mistral:TextChunk[]|mistral:DocumentURLChunk[]|mistral:ReferenceChunk[] {
            return error("Unsupported content type", cause = content);
        }
        string? stringContent = ();
        if content is string && content.length() > 0 {
            stringContent = content;
        } else if content is mistral:TextChunk[] {
            stringContent = string:'join("", ...content.'map(chunk => chunk.text));
        }

        mistral:ToolCall[]? toolCalls = message?.toolCalls;
        if toolCalls is () {
            return {role: ai:ASSISTANT, content: stringContent};
        }
        ai:FunctionCall[] functionCalls = [];
        foreach mistral:ToolCall toolcall in toolCalls {
            functionCalls.push(check self.mapToFunctionCall(toolcall));
        }
        return {role: ai:ASSISTANT, toolCalls: functionCalls, content: stringContent};
    }

    private isolated function mapToFunctionCall(mistral:ToolCall toolCall)
    returns ai:FunctionCall|ai:LlmError {
        do {
            record {}|string functionArgs = toolCall.'function.arguments;
            json jsonArgs = functionArgs is string ? check functionArgs.fromJsonString() : functionArgs.toJson();
            map<json>? arguments = check jsonArgs.cloneWithType();
            return {name: toolCall.'function.name, arguments, id: toolCall.id};

        } on fail error e {
            return error("Invalid or malformed arguments received in function call response.", e);
        }
    }

    private isolated function mapToMistralMessage(ai:ChatUserMessage|ai:ChatSystemMessage message)
    returns mistral:UserMessage|mistral:SystemMessage|ai:Error {
        if message is ai:ChatUserMessage {
            mistral:UserMessage userMessage = {
                role: ai:USER,
                content: check getChatMessageStringContent(message.content)
            };
            return userMessage;
        }

        mistral:SystemMessage systemMessage = {
            role: ai:SYSTEM,
            content: check getChatMessageStringContent(message.content)
        };
        return systemMessage;
    }
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        return messages.'map(msg => msg is ai:ChatUserMessage|ai:ChatSystemMessage ? check convertMessageToJson(msg) : msg);
    }
    if messages is ai:ChatUserMessage|ai:ChatSystemMessage {

    }
    return messages !is ai:ChatUserMessage|ai:ChatSystemMessage ? messages :
        {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
}

# Iterator that converts Mistral AI's Server-Sent Event stream into a stream of
# normalized `ai:ChatMessageChunk` values.
#
# Each `data:` payload is parsed into the Mistral wire chunk and mapped via
# `toAiChunk`; the terminating `[DONE]` sentinel, blank keep-alive lines and
# chunks that carry nothing for the caller are skipped. A malformed payload
# fails the stream rather than being skipped: the consumer must not receive a
# silently truncated answer that looks complete.
#
# Errors raised from inside the stream carry their detail in the message rather
# than as a cause: a query expression (`from ... in stream`) replaces an
# iterator's error with that error's cause, so a wrapped error would reach such a
# consumer as the raw underlying error instead of a typed `ai:Error`.
#
# The iterator owns the underlying SSE stream and closes it exactly once, on
# whichever end comes first: the `[DONE]` sentinel, exhaustion, an error, or an
# explicit close by the consumer. Ballerina does not close an iterator when its
# `next` returns `()`, so releasing the connection here is what keeps a completed
# stream from leaking it. The chat span is closed at the same points.
class MistralChunkIterator {
    private stream<http:SseEvent, error?> sseStream;
    private final observe:ChatSpan span;
    private boolean done = false;

    isolated function init(stream<http:SseEvent, error?> sseStream, observe:ChatSpan span) {
        self.sseStream = sseStream;
        self.span = span;
    }

    public isolated function next() returns record {|ai:ChatMessageChunk value;|}|ai:Error? {
        while !self.isDone() {
            record {|http:SseEvent value;|}|error? event = self.sseStream.next();
            if event is () {
                self.complete();
                return ();
            }
            if event is error {
                return self.failWith(error ai:LlmConnectionError(
                        string `Error while reading the model stream: ${event.message()}`));
            }
            string? data = event.value.data;
            if data is () {
                continue;
            }
            string trimmedData = data.trim();
            if trimmedData == "" {
                continue;
            }
            if trimmedData == DONE_SENTINEL {
                self.complete();
                return ();
            }
            CompletionChunk|error wireChunk = trimmedData.fromJsonStringWithType();
            if wireChunk is error {
                return self.failWith(error ai:LlmInvalidResponseError(
                        string `Invalid or malformed chunk received from the model while streaming: ${
                            wireChunk.message()}`));
            }
            foreach CompletionResponseStreamChoice choice in wireChunk.choices {
                if isAbortedFinishReason(choice.finish_reason) {
                    // The model aborted mid-generation. Returning `()` here would
                    // report the truncated answer as a complete one.
                    return self.failWith(error ai:LlmError(
                            "The model stopped generating due to an error before completing the response"));
                }
            }
            self.recordObservations(wireChunk);
            ai:ChatMessageChunk? chunk = toAiChunk(wireChunk);
            if chunk is ai:ChatMessageChunk {
                return {value: chunk};
            }
        }
        return ();
    }

    public isolated function close() returns ai:Error? {
        if self.markDone() {
            return ();
        }
        self.span.close();
        error? result = self.sseStream.close();
        if result is error {
            return error ai:LlmConnectionError("Error while closing the model stream", result);
        }
        return ();
    }

    # Reports the finish reason and token usage carried by a wire chunk to the span.
    # `ai:ChatMessageChunk` has no `usage` field, so this reads the wire chunk
    # directly rather than the mapped chunk. Mistral sends `usage` only on the
    # final chunk, so the usage counts are effectively recorded once per stream.
    #
    # + wireChunk - The parsed Mistral wire chunk just received
    private isolated function recordObservations(CompletionChunk wireChunk) {
        foreach CompletionResponseStreamChoice choice in wireChunk.choices {
            ai:FinishReason? finishReason = mapFinishReason(choice.finish_reason);
            if finishReason is ai:FinishReason {
                self.span.addFinishReason(finishReason);
                self.span.addOutputType(observe:TEXT);
            }
        }
        UsageInfo? usage = wireChunk?.usage;
        if usage is () {
            return;
        }
        int? promptTokens = usage.prompt_tokens;
        if promptTokens is int {
            self.span.addInputTokenCount(promptTokens);
        }
        int? completionTokens = usage.completion_tokens;
        if completionTokens is int {
            self.span.addOutputTokenCount(completionTokens);
        }
    }

    # Ends the stream cleanly: closes the span and releases the connection.
    private isolated function complete() {
        if self.markDone() {
            return;
        }
        self.span.close();
        error? result = self.sseStream.close();
        if result is error {
            // The stream already ended successfully; a failure to release the
            // connection must not turn that into an error for the consumer.
            log:printWarn("failed to close the Mistral AI response stream", 'error = result);
        }
    }

    # Ends the stream with an error: records it on the span, releases the
    # connection, and returns the error to hand back to the consumer.
    #
    # + err - The error that ended the stream
    # + return - The same error, for the caller to return
    private isolated function failWith(ai:Error err) returns ai:Error {
        if self.markDone() {
            return err;
        }
        self.span.close(err);
        error? result = self.sseStream.close();
        if result is error {
            log:printWarn("failed to close the Mistral AI response stream", 'error = result);
        }
        return err;
    }

    private isolated function isDone() returns boolean {
        lock {
            return self.done;
        }
    }

    # Marks the stream as done, returning whether it was already done before this
    # call - so that closing and span-closing happen exactly once.
    #
    # + return - Whether the stream had already been marked done
    private isolated function markDone() returns boolean {
        lock {
            boolean wasDone = self.done;
            self.done = true;
            return wasDone;
        }
    }
}

# Closes a chat span with the given error and returns that error, so a failing
# `chatAsStream` setup step stays a single expression at the call site.
#
# + span - The span to close
# + err - The error that ended the request
# + return - The same error
isolated function closeSpanWith(observe:ChatSpan span, ai:Error err) returns ai:Error {
    span.close(err);
    return err;
}

# Extracts a short, human-readable detail from a non-2xx streaming response, for
# use in the error message. Falls back to the status code when the body is not
# readable JSON, and truncates so an unexpectedly large body cannot dominate.
#
# + response - The non-2xx response from the model
# + return - The detail to quote in the error message
isolated function getErrorResponseDetail(http:Response response) returns string {
    json|error errorPayload = response.getJsonPayload();
    if errorPayload is error {
        return string `no error details in the response body`;
    }
    string detail = errorPayload.toJsonString();
    return detail.length() > MAX_ERROR_DETAIL_LENGTH ?
        detail.substring(0, MAX_ERROR_DETAIL_LENGTH) + "..." : detail;
}

# Projects a normalized `ai:ChatMessageChunk` stream onto its answer text,
# yielding each non-empty `content` fragment and skipping tool-call, reasoning
# and finish-only chunks. Backs `generateAsStream`; closing it closes the
# underlying chunk stream.
class ChunkTextIterator {
    private final stream<ai:ChatMessageChunk, ai:Error?> chunks;

    isolated function init(stream<ai:ChatMessageChunk, ai:Error?> chunks) {
        self.chunks = chunks;
    }

    public isolated function next() returns record {|string value;|}|ai:Error? {
        while true {
            record {|ai:ChatMessageChunk value;|}|ai:Error? next = self.chunks.next();
            if next is () {
                return ();
            }
            if next is ai:Error {
                return next;
            }
            string? content = next.value.content;
            if content is string && content.length() > 0 {
                return {value: content};
            }
        }
    }

    public isolated function close() returns ai:Error? {
        return self.chunks.close();
    }
}
